// ERROR ACTION TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//USER ACTION TYPES
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// BIKE ACTION TYPES
export const ADD_BIKE = "ADD_BIKE";
export const GET_BIKES = "GET_BIKES";
export const GET_BIKE_INFO = "GET_BIKE_INFO";
export const DELETE_BIKE = "DELETE_BIKE";
export const ADD_BIKE_FAIL = "ADD_BIKE_FAIL";
export const GET_BIKES_FAIL = "GET_BIKES_FAIL";
export const DELETE_BIKE_FAIL = "DELETE_BIKE_FAIL";
export const GET_BIKE_INFO_FAIL = "GET_BIKE_INFO_FAIL";
export const BIKES_LOADING = "BIKES_LOADING";

// ORDER ACTION TYPES
export const GET_ORDERS = "GET_ALL_ORDERS";
export const GET_ORDER_INFO = "GET_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const ADD_BIKE_TO_ORDER = "ADD_BIKE_TO_ORDER";
export const REMOVE_BIKE_FROM_ORDER = "REMOVE_BIKE_FROM_ORDER";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";
export const DELETE_ORDER = "DELETE_ORDER";
export const CLEAR_CART = "CLEAR_CART";
export const SET_DELIVERY_TIME = "SET_DELIVERY_TIME";
export const SET_DELIVERY_TYPE = "SET_DELIVERY_TYPE";

// PAYMENT ACTION TYPES
export const CREATE_PAYMENT_INTENT_SUCCESS = "CREATE_PAYMENT_INTENT_SUCCESS";
export const CREATE_PAYMENT_INTENT_FAIL = "CREATE_PAYMENT_INTENT_FAIL";
export const CONFIRM_CARD_PAYMENT_SUCCESS = "CONFIRM_CARD_PAYMENT_SUCCESS";
export const CONFIRM_CARD_PAYMENT_FAIL = "CONFIRM_CARD_PAYMENT_FAIL";
export const PAYMENT_PROCESSING = "PAYMENT_PROCESSING";
export const LOAD_CHECKOUT = "LOAD_CHECKOUT";
export const FINISH_CHECKOUT = "FINISH_CHECKOUT";
